package com.jcircle.dynamodb.entity;

import lombok.Data;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.cloud.context.config.annotation.RefreshScope;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;


@Data
@AllArgsConstructor
@RefreshScope
@NoArgsConstructor
@DynamoDBTable(tableName = "employee")
public class Employee {
	
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String empid;
	 @Value("${orgId}")
	@DynamoDBAttribute
	private String orgId;
	@DynamoDBAttribute
	private String firstName;
	@DynamoDBAttribute
	private String lastName;
	@DynamoDBAttribute
	private String email;
	@DynamoDBAttribute
	private Department department;
	
	

}
